[package]
name = "logix-xtask"
version = "0.1.0"
edition = "2021"
authors = [
  "Bjørn Ove Hay Andersen <bjrnove@gmail.com>",
  "Gigantos <gigantos@gigantos.net>",
]
license = "MPL-2.0"

[dependencies]

[workspace]
members = ["xtask"]
